In [2]:
import pandas as pd
import numpy as np

In [3]:
path = "Vinhomes Smart City - 18032022.csv"
df1 = pd.read_csv(path)
df1.head()

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Đơn giá thông thủy,...,Giá gồm VAT và KPBT,Đơn giá gồm CSBH,CK TTTTD (7%),"Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)",Miễn 5 năm DV,Nội thất,CK BLNH (0.8%),Giá NET,Đơn giá NET,Tổng quà tặng
0,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"46,970,130",...,"1,654,608,306","46,970,130","103,569,136","43,682,220","22,050,000","70,000,000","11,836,473","1,272,103,473","40,384,237","207,455,608"
1,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"46,337,884",...,"1,767,032,432","46,337,884","110,608,529","43,094,232","23,870,000","70,000,000","12,640,975","1,363,002,344","39,970,743","217,119,504"
2,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"46,137,247",...,"4,215,264,042","46,137,247","263,858,914","42,907,640","57,190,000","120,000,000","30,155,305","3,298,208,845","40,369,753","471,204,219"
3,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"51,066,182",...,"4,432,110,573","51,066,182","277,391,503","47,491,550","54,320,000","120,000,000","31,701,886","3,479,322,364","44,836,628","483,413,389"
4,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"48,423,590",...,"1,705,886,379","48,423,590","106,774,015","45,033,938","22,050,000","70,000,000","12,202,745","1,314,316,315","41,724,327","211,026,760"

In [4]:
path = 'Vinhomes Smart City - 24062022.csv'
df2 = pd.read_csv(path)
df2.head()

,Dự án,Phân khu,Toà,Mã căn,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,...,"Đơn giá gồm CSBH (exc VAT, KPBT)",CK TTTTD (7%),"Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)",Miễn 5 năm DV,Quà tặng chào hè,Nội thất,CK BLNH (0.8%),Giá NET,Đơn giá NET,Tổng quà tặng
0,Vinhomes Smart City,Sakura,SA2,SA23810,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,743,636,136","4,186,663,494",...,47811444.90,"262,054,530","44,464,644","54,810,000","30,000,000","120,000,000","33,493,308","3,273,278,297","41,804,321","238,303,308"
1,Vinhomes Smart City,Sakura,SA2,SA23805,3PN,Đông Nam- Tây Nam,75.5,NaN,"3,541,123,520","3,960,071,397",...,46902298.28,"247,878,646","43,619,137","52,850,000","30,000,000","120,000,000","31,680,571","3,088,714,300","40,910,123","234,530,571"
2,Vinhomes Smart City,Sakura,SA2,SA23710,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,777,591,062","4,224,693,010",...,48245096.58,"264,431,374","44,867,940","54,810,000","30,000,000","120,000,000","33,797,544","3,304,552,142","42,203,731","238,607,544"
3,Vinhomes Smart City,Sakura,SA2,SA23705,3PN,Đông Nam- Tây Nam,75.5,NaN,"3,572,755,520","3,995,499,237",...,47321265.17,"250,092,886","44,008,777","52,850,000","30,000,000","120,000,000","31,963,994","3,117,848,638","41,296,008","234,813,994"
4,Vinhomes Smart City,Sakura,SA2,SA23610,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,811,546,156","4,262,722,716",...,48678750.40,"266,808,231","45,271,238","54,810,000","30,000,000","120,000,000","34,101,782","3,335,826,141","42,603,144","238,911,782"

In [5]:
for i,v in enumerate(df1.columns):
    print(i,v)

0 Dự án
1 Tòa
2 Phân khu
3 Mã căn
4 Tầng
5 Loại căn hộ
6 Hướng ban công
7 Diện tích thông thủy
8 Diện tích tim tường
9 Đơn giá thông thủy
10 Giá chưa VAT và KPBT
11 Giá gồm VAT và KPBT
12 Đơn giá gồm CSBH
13 CK TTTTD (7%)
14 Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)
15 Miễn 5 năm DV
16 Nội thất
17 CK BLNH (0.8%)
18 Giá NET
19 Đơn giá NET
20 Tổng quà tặng

In [6]:
for i,v in enumerate(df2.columns):
    print(i,v)

0 Dự án
1 Phân khu
2 Toà
3 Mã căn
4 Loại căn hộ
5 Hướng ban công
6 Diện tích thông thủy
7 Diện tích tim tường
8 Giá chưa VAT và KPBT
9 Giá gồm VAT và KPBT
10 Ngày Nhập Quỹ
11 Đơn giá gồm CSBH (exc VAT, KPBT)
12 CK TTTTD (7%)
13 Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)
14 Miễn 5 năm DV
15 Quà tặng chào hè
16 Nội thất
17 CK BLNH (0.8%)
18 Giá NET
19 Đơn giá NET
20 Tổng quà tặng

In [7]:
# thử union 2 dataframes

df_test = pd.concat([df1,df2])
df_test.head()

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Đơn giá thông thủy,...,Miễn 5 năm DV,Nội thất,CK BLNH (0.8%),Giá NET,Đơn giá NET,Tổng quà tặng,Toà,Ngày Nhập Quỹ,"Đơn giá gồm CSBH (exc VAT, KPBT)",Quà tặng chào hè
0,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,Studio,South West - Tây Nam,31.5,34.8,"46,970,130",...,"22,050,000","70,000,000","11,836,473","1,272,103,473","40,384,237","207,455,608",NaN,NaN,NaN,NaN
1,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,1PN,North East - Đông Bắc,34.1,37.5,"46,337,884",...,"23,870,000","70,000,000","12,640,975","1,363,002,344","39,970,743","217,119,504",NaN,NaN,NaN,NaN
2,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,3PN,Đông Bắc- Đông Nam,81.7,90.5,"46,137,247",...,"57,190,000","120,000,000","30,155,305","3,298,208,845","40,369,753","471,204,219",NaN,NaN,NaN,NaN
3,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,3PN,Tây Bắc- Tây Nam,77.6,87.7,"51,066,182",...,"54,320,000","120,000,000","31,701,886","3,479,322,364","44,836,628","483,413,389",NaN,NaN,NaN,NaN
4,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,Studio,South West - Tây Nam,31.5,34.8,"48,423,590",...,"22,050,000","70,000,000","12,202,745","1,314,316,315","41,724,327","211,026,760",NaN,NaN,NaN,NaN

In [8]:
for i,v in enumerate(df_test.columns):
    print(i,v)

0 Dự án
1 Tòa
2 Phân khu
3 Mã căn
4 Tầng
5 Loại căn hộ
6 Hướng ban công
7 Diện tích thông thủy
8 Diện tích tim tường
9 Đơn giá thông thủy
10 Giá chưa VAT và KPBT
11 Giá gồm VAT và KPBT
12 Đơn giá gồm CSBH
13 CK TTTTD (7%)
14 Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)
15 Miễn 5 năm DV
16 Nội thất
17 CK BLNH (0.8%)
18 Giá NET
19 Đơn giá NET
20 Tổng quà tặng
21 Toà
22 Ngày Nhập Quỹ
23 Đơn giá gồm CSBH (exc VAT, KPBT)
24 Quà tặng chào hè

In [9]:
list(df_test.columns)

['Dự án',
 'Tòa',
 'Phân khu',
 'Mã căn',
 'Tầng',
 'Loại căn hộ',
 'Hướng ban công',
 'Diện tích thông thủy',
 'Diện tích tim tường',
 'Đơn giá thông thủy',
 'Giá chưa VAT và KPBT',
 'Giá gồm VAT và KPBT',
 'Đơn giá gồm CSBH',
 'CK TTTTD (7%)',
 'Đơn giá gồm CSBH (ex VAT, KPBT, CK TTTTĐ)',
 'Miễn 5 năm DV',
 'Nội thất',
 'CK BLNH (0.8%)',
 'Giá NET',
 'Đơn giá NET',
 'Tổng quà tặng',
 'Toà',
 'Ngày Nhập Quỹ',
 'Đơn giá gồm CSBH (exc VAT, KPBT)',
 'Quà tặng chào hè']

In [10]:
# Dưới là những cột cần lấy sau khi union -> có cách nào nhanh hơn thay vì gõ tay k?
col_labels = ['Ngày cập nhật', 'Dự án', 'Tòa', 'Phân khu', 'Mã căn', 'Tầng', 'Khoảng tầng', 'Loại căn hộ', 'Hướng ban công', 'Diện tích thông thủy', 'Diện tích tim tường', 'Giá chưa VAT và KPBT', 'Giá gồm VAT và KPBT', 'Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)', 'Tổng quà tặng', 'Giá NET', 'Đơn giá NET']
col1 = ['Dự án', 'Tòa', 'Phân khu', 'Mã căn', 'Tầng', 'Loại căn hộ', 'Hướng ban công', 'Diện tích thông thủy', 'Diện tích tim tường', 'Giá chưa VAT và KPBT', 'Giá gồm VAT và KPBT', 'Tổng quà tặng', 'Giá NET', 'Đơn giá NET']
col2 = ['Dự án', 'Phân khu', 'Mã căn', 'Loại căn hộ', 'Hướng ban công', 'Diện tích thông thủy', 'Diện tích tim tường', 'Giá chưa VAT và KPBT', 'Giá gồm VAT và KPBT', 'Tổng quà tặng', 'Giá NET', 'Đơn giá NET']

In [11]:
print(len(col1))
print(len(col2))

14
12

In [12]:
# lấy ra trong df1 những cột thuộc list col1
df1 = df1[col1]
df1.head()

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"

In [13]:
# lấy ra trong df2 những cột thuộc list col2
df2 = df2[col2]
df2.head()

,Dự án,Phân khu,Mã căn,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,Vinhomes Smart City,Sakura,SA23810,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,743,636,136","4,186,663,494","238,303,308","3,273,278,297","41,804,321"
1,Vinhomes Smart City,Sakura,SA23805,3PN,Đông Nam- Tây Nam,75.5,NaN,"3,541,123,520","3,960,071,397","234,530,571","3,088,714,300","40,910,123"
2,Vinhomes Smart City,Sakura,SA23710,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,777,591,062","4,224,693,010","238,607,544","3,304,552,142","42,203,731"
3,Vinhomes Smart City,Sakura,SA23705,3PN,Đông Nam- Tây Nam,75.5,NaN,"3,572,755,520","3,995,499,237","234,813,994","3,117,848,638","41,296,008"
4,Vinhomes Smart City,Sakura,SA23610,3PN,Tây Bắc- Tây Nam,78.3,NaN,"3,811,546,156","4,262,722,716","238,911,782","3,335,826,141","42,603,144"

In [14]:
# union 2 dataframes sau khi đã lọc cột
df_test = pd.concat([df1,df2])
df_test

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Vinhomes Smart City,NaN,Sakura,SA23112,NaN,1PN + 1,South West - Tây Nam,42.9,46.5,"2,055,808,990","2,299,104,215","118,422,834","1,793,479,525","41,806,050"
81,Vinhomes Smart City,NaN,Sakura,SA23210,NaN,3PN,Tây Bắc- Tây Nam,78.3,87.7,"3,940,575,277","4,407,235,332","240,067,883","3,454,667,123","44,120,908"
82,Vinhomes Smart City,NaN,Sakura,SA23304,NaN,3PN,Đông Bắc- Đông Nam,82.4,90.6,"3,972,331,379","4,442,477,047","243,219,816","3,481,048,364","42,245,733"
83,Vinhomes Smart City,NaN,Sakura,SA23414,NaN,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,796,585,530","4,245,895,447","239,407,164","3,321,417,377","41,937,088"
84,Vinhomes Smart City,NaN,Sakura,SA23814,NaN,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,660,765,626","4,093,777,155","238,190,217","3,196,321,813","40,357,599"

In [15]:
for i,v in enumerate(df_test.columns):
    print(i,v)

0 Dự án
1 Tòa
2 Phân khu
3 Mã căn
4 Tầng
5 Loại căn hộ
6 Hướng ban công
7 Diện tích thông thủy
8 Diện tích tim tường
9 Giá chưa VAT và KPBT
10 Giá gồm VAT và KPBT
11 Tổng quà tặng
12 Giá NET
13 Đơn giá NET

In [16]:
df_test.to_csv('union.csv', encoding='utf-8')

In [17]:
# download data into a xlsx file
df_test.to_excel('union-test.xlsx', sheet_name='vinhomes-smart-city-union', encoding='utf-8', index=False)

'''
- sheet_name: tên của tab
- encoding: để k bị lỗi vietkey
- index=False: khi mở file xlsx dưới lap thì sẽ tự động bỏ cột index đi
'''

'\n- sheet_name: tên của tab\n- encoding: để k bị lỗi vietkey\n- index=False: khi mở file xlsx dưới lap thì sẽ tự động bỏ cột index đi\n'

In [18]:
# khi union 2 df lại với nhau -> index đang bị lẫn của cả 2 df -> reset lại index
df_test.reset_index(drop=True, inplace=True)
df_test

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,Vinhomes Smart City,NaN,Sakura,SA23112,NaN,1PN + 1,South West - Tây Nam,42.9,46.5,"2,055,808,990","2,299,104,215","118,422,834","1,793,479,525","41,806,050"
315,Vinhomes Smart City,NaN,Sakura,SA23210,NaN,3PN,Tây Bắc- Tây Nam,78.3,87.7,"3,940,575,277","4,407,235,332","240,067,883","3,454,667,123","44,120,908"
316,Vinhomes Smart City,NaN,Sakura,SA23304,NaN,3PN,Đông Bắc- Đông Nam,82.4,90.6,"3,972,331,379","4,442,477,047","243,219,816","3,481,048,364","42,245,733"
317,Vinhomes Smart City,NaN,Sakura,SA23414,NaN,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,796,585,530","4,245,895,447","239,407,164","3,321,417,377","41,937,088"
318,Vinhomes Smart City,NaN,Sakura,SA23814,NaN,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,660,765,626","4,093,777,155","238,190,217","3,196,321,813","40,357,599"

In [19]:
# tạo ra cột ngày riêng cho 2 df
updated_date_1 = [18032022]
updated_date_2 = [24062022]

x = list(updated_date_1 * len(df1))
y = list(updated_date_2 * len(df2))

In [20]:
# cách 1: gán giá trị của list x, y vào cột mới (tên đc specified trong '') -> cột mới add vào cuối cùng
df1['Ngày cập nhật'] = x
df2['Ngày cập nhât'] = y

In [21]:
# cách 2: dùng hàm insert -> có thể assign vị trí của cột mới
df1.insert(0, 'Ngày cập nhật', x, True)

In [22]:
# lấy số dòng của df
len(df_test)

319

In [23]:
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET,Ngày cập nhật
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237",18032022
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743",18032022
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753",18032022
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628",18032022
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327",18032022

In [24]:
# drop 1 cột
df1.drop('Ngày cập nhật', inplace=True, axis=1)

'''
- inplace=True: diễn ra ngày trong original object
- axis=1: xóa cột chứ kp dòng
'''

'\n- inplace=True: diễn ra ngày trong original object\n- axis=1: xóa cột chứ kp dòng\n'

In [25]:
df1.head()

,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"

In [26]:
df1.insert(0, 'Ngày cập nhật', x, True)
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"

In [27]:
df1.drop(df1.columns[-1], axis=1, inplace=True)
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"

In [28]:
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"

In [30]:
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"

In [ ]:
df1.drop(df1.columns[0], axis=1, inplace=True)

In [31]:
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"

In [ ]:
for i,v in enumerate(df1.columns):
    print(i,v)

0 Dự án
1 Tòa
2 Phân khu
3 Mã căn
4 Tầng
5 Loại căn hộ
6 Hướng ban công
7 Diện tích thông thủy
8 Diện tích tim tường
9 Giá chưa VAT và KPBT
10 Giá gồm VAT và KPBT
11 Tổng quà tặng
12 Giá NET
13 Đơn giá NET

In [ ]:
df1.insert(0,'Ngày cập nhật',x)
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Đơn giá NET
0,18032022,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473","40,384,237"
1,18032022,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344","39,970,743"
2,18032022,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845","40,369,753"
3,18032022,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364","44,836,628"
4,18032022,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315","41,724,327"

In [32]:
# chuyển type của cột Ngày cập nhật từ string sang datetime
df1['Ngày cập nhật'] = pd.to_datetime(df1['Ngày cập nhật'], format='%d%m%Y')
df1.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"

In [ ]:
df1.columns[0] = pd.to_datetime(df1.columns[0], format='%d%m%Y')
df1.head()

# lỗi: vì df1.columns[0] chỉ trả về tên cột ở index=0 (dạng string)

ValueError: time data 'Ngày cập nhật' does not match format '%d%m%Y' (match)

In [ ]:
# trả về series gồm tất cả các giá trị ở cột có index=0
df1[df1.columns[0]]

0     2022-03-18
1     2022-03-18
2     2022-03-18
3     2022-03-18
4     2022-03-18
         ...
229   2022-03-18
230   2022-03-18
231   2022-03-18
232   2022-03-18
233   2022-03-18
Name: Ngày cập nhật, Length: 234, dtype: datetime64[ns]

In [ ]:
# cách 2
df1.iloc[:, 0]

0     2022-03-18
1     2022-03-18
2     2022-03-18
3     2022-03-18
4     2022-03-18
         ...
229   2022-03-18
230   2022-03-18
231   2022-03-18
232   2022-03-18
233   2022-03-18
Name: Ngày cập nhật, Length: 234, dtype: datetime64[ns]

In [ ]:
print(col_labels)

['Ngày cập nhật', 'Dự án', 'Tòa', 'Phân khu', 'Mã căn', 'Tầng', 'Khoảng tầng', 'Loại căn hộ', 'Hướng ban công', 'Diện tích thông thủy', 'Diện tích tim tường', 'Giá chưa VAT và KPBT', 'Giá gồm VAT và KPBT', 'Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)', 'Tổng quà tặng', 'Giá NET', 'Đơn giá NET']

In [33]:
# lấy ra những cột trong df1 mà giao với col_labels (inner join)
test_2 = df1[df1.columns.intersection(col_labels)]
test_2

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23811,38,Studio,South West - Tây Nam,31.6,34.8,"1,394,749,226","1,559,613,338","200,910,440","1,193,838,786"
230,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23812,38,1PN + 1,South West - Tây Nam,42.9,46.5,"1,880,568,885","2,102,835,297","246,714,373","1,633,854,512"
231,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23814,38,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,554,141,346","3,974,357,961","452,663,025","3,101,478,321"
232,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23817,38,2PN,North East - Đông Bắc,54.6,59.1,"2,255,358,187","2,521,671,537","334,137,939","1,921,220,248"
233,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23818,38,2PN,North East - Đông Bắc,54.6,59.1,"2,248,693,663","2,514,207,270","333,618,106","1,915,075,557"

In [34]:
# cách 2 để lấy ra những cột cần
df1 = df1.filter(col_labels)
df1

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473"
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344"
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845"
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364"
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23811,38,Studio,South West - Tây Nam,31.6,34.8,"1,394,749,226","1,559,613,338","200,910,440","1,193,838,786"
230,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23812,38,1PN + 1,South West - Tây Nam,42.9,46.5,"1,880,568,885","2,102,835,297","246,714,373","1,633,854,512"
231,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23814,38,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,554,141,346","3,974,357,961","452,663,025","3,101,478,321"
232,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23817,38,2PN,North East - Đông Bắc,54.6,59.1,"2,255,358,187","2,521,671,537","334,137,939","1,921,220,248"
233,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23818,38,2PN,North East - Đông Bắc,54.6,59.1,"2,248,693,663","2,514,207,270","333,618,106","1,915,075,557"

In [ ]:
type(pd.Series(col_labels))

pandas.core.series.Series

In [ ]:
type(pd.Series(df1.columns))

pandas.core.series.Series

In [35]:
# lấy ra tên những cột k giao nhau

a = pd.Series(col_labels)
b = pd.Series(df1.columns)
missing_col = a[~a.isin(b)]
missing_col = list(missing_col)

In [36]:
# tạo df rỗng với tên cột
df_null = pd.DataFrame(columns=missing_col)
df_null

Empty DataFrame
Columns: [Khoảng tầng, Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ), Đơn giá NET]
Index: []

In [37]:
# thử union 2 dataframes

df_test = pd.concat([df1,df_null])
df_test.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,Tổng quà tặng,Giá NET,Khoảng tầng,"Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)",Đơn giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306","207,455,608","1,272,103,473",NaN,NaN,NaN
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432","217,119,504","1,363,002,344",NaN,NaN,NaN
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042","471,204,219","3,298,208,845",NaN,NaN,NaN
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573","483,413,389","3,479,322,364",NaN,NaN,NaN
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379","211,026,760","1,314,316,315",NaN,NaN,NaN

In [38]:
# sắp xếp lại vị trí các cột trong df theo thứ tự tên cột trong list col_labels
df_rearrange = df_test.reindex(col_labels, axis=1)
df_rearrange

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Khoảng tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,"Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)",Tổng quà tặng,Giá NET,Đơn giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,NaN,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306",NaN,"207,455,608","1,272,103,473",NaN
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,NaN,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432",NaN,"217,119,504","1,363,002,344",NaN
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,NaN,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042",NaN,"471,204,219","3,298,208,845",NaN
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,NaN,3PN,Tây Bắc- Tây Nam,77.6,87.7,"3,962,735,753","4,432,110,573",NaN,"483,413,389","3,479,322,364",NaN
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,NaN,Studio,South West - Tây Nam,31.5,34.8,"1,525,343,075","1,705,886,379",NaN,"211,026,760","1,314,316,315",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23811,38.0,NaN,Studio,South West - Tây Nam,31.6,34.8,"1,394,749,226","1,559,613,338",NaN,"200,910,440","1,193,838,786",NaN
230,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23812,38.0,NaN,1PN + 1,South West - Tây Nam,42.9,46.5,"1,880,568,885","2,102,835,297",NaN,"246,714,373","1,633,854,512",NaN
231,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23814,38.0,NaN,3PN,Tây Bắc- Tây Nam,79.2,87.7,"3,554,141,346","3,974,357,961",NaN,"452,663,025","3,101,478,321",NaN
232,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23817,38.0,NaN,2PN,North East - Đông Bắc,54.6,59.1,"2,255,358,187","2,521,671,537",NaN,"334,137,939","1,921,220,248",NaN
233,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA23818,38.0,NaN,2PN,North East - Đông Bắc,54.6,59.1,"2,248,693,663","2,514,207,270",NaN,"333,618,106","1,915,075,557",NaN

In [41]:
test = df_rearrange
test.head(3)

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Khoảng tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,"Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)",Tổng quà tặng,Giá NET,Đơn giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,NaN,Studio,South West - Tây Nam,31.5,34.8,"1,479,559,081","1,654,608,306",NaN,"207,455,608","1,272,103,473",NaN
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,NaN,1PN,North East - Đông Bắc,34.1,37.5,"1,580,121,848","1,767,032,432",NaN,"217,119,504","1,363,002,344",NaN
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,NaN,3PN,Đông Bắc- Đông Nam,81.7,90.5,"3,769,413,064","4,215,264,042",NaN,"471,204,219","3,298,208,845",NaN

In [40]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Ngày cập nhật                               234 non-null    datetime64[ns]
 1   Dự án                                       234 non-null    object
 2   Tòa                                         234 non-null    object
 3   Phân khu                                    234 non-null    object
 4   Mã căn                                      234 non-null    object
 5   Tầng                                        234 non-null    float64
 6   Khoảng tầng                                 0 non-null      object
 7   Loại căn hộ                                 234 non-null    object
 8   Hướng ban công                              234 non-null    object
 9   Diện tích thông thủy                        234 non-null    float64
 10  Diện tích tim tường                         234 non-null    float64
 11  Giá chưa VAT và KPBT                        234 non-null    object
 12  Giá gồm VAT và KPBT                         234 non-null    object
 13  Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)  0 non-null      object
 14  Tổng quà tặng                               234 non-null    object
 15  Giá NET                                     234 non-null    object
 16  Đơn giá NET                                 0 non-null      object
dtypes: datetime64[ns](1), float64(3), object(13)
memory usage: 32.9+ KB

In [108]:
test.iloc[:,-2].astype(np.int64)

0      1272103473
1      1363002344
2      3298208845
3      3479322364
4      1314316315
          ...
229    1193838786
230    1633854512
231    3101478321
232    1921220248
233    1915075557
Name: Giá NET, Length: 234, dtype: int64

In [96]:
for x in range (12,16,1): # cột index=16 là null
    test[test.columns[x]] = test[test.columns[x]].str.replace(',','').astype(float)
    x +=1
test.info()

AttributeError: Can only use .str accessor with string values!

In [93]:
# ilox[row,col]
test.iloc[11].str.replace(',','').astype(int)

ValueError: value must be an integer, received <class 'str'> for year

In [74]:
test.head()

,Ngày cập nhật,Dự án,Tòa,Phân khu,Mã căn,Tầng,Khoảng tầng,Loại căn hộ,Hướng ban công,Diện tích thông thủy,Diện tích tim tường,Giá chưa VAT và KPBT,Giá gồm VAT và KPBT,"Đơn giá gồm CSBH (exc VAT, KPBT, CK TTTTĐ)",Tổng quà tặng,Giá NET,Đơn giá NET
0,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20211,2.0,NaN,Studio,South West - Tây Nam,31.5,34.8,1.479559e+09,1.654608e+09,NaN,207455608.0,1.272103e+09,NaN
1,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20503,5.0,NaN,1PN,North East - Đông Bắc,34.1,37.5,1.580122e+09,1.767032e+09,NaN,217119504.0,1.363002e+09,NaN
2,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20504,5.0,NaN,3PN,Đông Bắc- Đông Nam,81.7,90.5,3.769413e+09,4.215264e+09,NaN,471204219.0,3.298209e+09,NaN
3,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20510,5.0,NaN,3PN,Tây Bắc- Tây Nam,77.6,87.7,3.962736e+09,4.432111e+09,NaN,483413389.0,3.479322e+09,NaN
4,2022-03-18,Vinhomes Smart City,SA2,Sakura,SA20511,5.0,NaN,Studio,South West - Tây Nam,31.5,34.8,1.525343e+09,1.705886e+09,NaN,211026760.0,1.314316e+09,NaN

In [90]:
# df_final.to_excel('union_final.xlsx', sheet_name='vinhomes-smart-city-union', encoding='utf-8', index=False)

table.to_excel('caculation.xlsx', sheet_name='table_calculation', encoding='utf-8')

In [91]:
# max(giá chưa VAT và KPBT) theo loại căn hộ

calculation = test.groupby('Loại căn hộ').agg({'Giá chưa VAT và KPBT':['max','min'], 'Giá gồm VAT và KPBT':['max','min']})
# calculation = calculation.rename(columns={'Giá chưa VAT và KPBT':'Max Giá chưa bao gồm', 'Giá gồm VAT và KPBT':'Min Giá bao gồm'})
table = pd.DataFrame(calculation)
table

                   Giá chưa VAT và KPBT               Giá gồm VAT và KPBT  \
                                    max           min                 max
Loại căn hộ
1PN                        1.684868e+09  1.545317e+09        1.884332e+09
1PN + 1                    2.132268e+09  1.880569e+09        2.384739e+09
2PN                        2.530830e+09  2.248694e+09        2.830200e+09
2PN + 1 (2 Toilet)         3.202834e+09  2.919304e+09        3.582155e+09
3PN                        4.129081e+09  3.437984e+09        4.618037e+09
Studio                     1.583118e+09  1.267661e+09        1.770586e+09


                             min
Loại căn hộ
1PN                 1.728035e+09
1PN + 1             2.102835e+09
2PN                 2.514207e+09
2PN + 1 (2 Toilet)  3.264601e+09
3PN                 3.844555e+09
Studio              1.417568e+09